---
- name: Deploy NTP and Monitoring
  hosts: ntp_servers
  become: yes
  roles:
    - { role: ntp, tags: ['ntp'] }

- name: Deploy Nagios Monitoring
  hosts: nagios_server
  become: yes
  roles:
    - { role: nagios, tags: ['nagios'] }
