---
- name: Install ntp package
  apt:
    name: ntp
    state: present
    update_cache: yes

- name: Deploy NTP configuration
  template:
    src: ntpd.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart ntp service
