---
- name: Deploy Nagios host configuration
  template:
    src: nagios_host.cfg.j2
    dest: /etc/nagios/conf.d/{{ inventory_hostname }}_host.cfg
    owner: nagios
    group: nagios
    mode: '0644'

- name: Deploy Nagios service configuration
  template:
    src: nagios_service.cfg.j2
    dest: /etc/nagios/conf.d/{{ inventory_hostname }}_service.cfg
    owner: nagios
    group: nagios
    mode: '0644'

- name: Restart Nagios service
  service:
    name: nagios
    state: restarted
